# Site settings
title: Dana Data Life
author:
  name: Dana Hagist
  email: dhagist@gmail.com
description: "Sharing me, my passion for data, and my life"

# Build settings
remote_theme: jekyll/minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
