# Site settings
title: Dana Data Life
author: Dana Hagist
email: dhagist@gmail.com
description: "Sharing me, my passion for data, and my life"

# Build settings
markdown: kramdown
theme: minima

plugins:
 - jekyll-feed
 - jekyll-gist

